# Welcome to Jekyll!
#

# Site settings
title: Demo effect
description: |
  I swear the code was working 5 minutes ago...

  powered by [HTML5 UP](http://html5up.net)
owner: Olli Väinölä # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: olli.m.vainola@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ovainola.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/ovainola
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
highlighter: rouge
array: []
google_analytics: UA-78949639-1
#sass:
#  style: compressed
